---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/Vriddhachalam-Anjane/airbyte-platform/blob/0.50.37/airbyte-config/models/src/main/resources/types/NotificationConfiguration.yaml
title: Notification
description: Notification Configuration
type: object
required:
  - notificationType
additionalProperties: true
properties:
  notificationType:
    "$ref": NotificationConfigurationType.yaml
  enabled:
    type: boolean
    default: false
