---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/Vriddhachalam-Anjane/airbyte-platform/blob/0.50.37/airbyte-config/models/src/main/resources/types/SlackNotificationConfiguration.yaml
title: SlackNotificationConfiguration
description: Slack Notification Settings
type: object
required:
  - webhook
additionalProperties: true
properties:
  webhook:
    type: string
