---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/Vriddhachalam-Anjane/airbyte-platform/blob/0.50.37/airbyte-config/models/src/main/resources/types/VaultSecretPersistenceConfig.yaml
title: VaultSecretPersistenceConfig
description: Vault SecretPersistenceConfig to be passed into the RuntimeSecretPersistence class.
type: object
additionalProperties: true
properties:
  data:
    address:
      description: Vault address
      type: String
    token:
      description: Vault token
      type: String
    prefix:
      description: Vault prefix
      type: String
